Repository Project-C-SQL/postgresql-for-novices, pull requests merged in 2022-11, with the labels that each got.

#43 Feat/sqlparser columns
  src/pg4n/sqlparser.py
  src/pg4n/test/test_sqlparser.py
Labels: enhancement, parser

#44 Improve QEPs
  README.md
  src/pg4n/qepparser.py
  src/pg4n/test/test_qepparser.py
Labels: enhancement, qep

#57 Feat/subquery orderby
  src/pg4n/orderby.py
  src/pg4n/subquery_orderby_checker.py
  src/pg4n/test/test_subquery_orderby_checker.py
Labels: enhancement, semantics

#58 Feat/subquery select
  src/pg4n/subquery_select_checker.py
  src/pg4n/test/test_subquery_select_checker.py
Labels: enhancement, semantics

#59 Feat/implied expression
  src/pg4n/implied_expression_checker.py
  src/pg4n/qepparser.py
  src/pg4n/test/test_implied_expression_checker.py
Labels: enhancement, semantics

#65 Fix/subquery select
  src/pg4n/sqlparser.py
  src/pg4n/subquery_select_checker.py
  src/pg4n/test/test_subquery_select_checker.py
Labels: bug, semantics

#71 Feat/strange having
  src/pg4n/strange_having_checker.py
  src/pg4n/test/test_strange_having_checker.py
Labels: enhancement, semantics

#73 Feat/sum distinct
  src/pg4n/sum_distinct_checker.py
  src/pg4n/test/test_sum_distinct_checker.py
Labels: enhancement, semantics

#75 Feat/eq wildcard
  src/pg4n/eq_wildcard_checker.py
  src/pg4n/test/test_eq_wildcard_checker.py
Labels: enhancement, semantics

#77 Feat/errfmt
  src/pg4n/cmp_domain_checker.py
  src/pg4n/eq_wildcard_checker.py
  src/pg4n/errfmt.py
  src/pg4n/implied_expression_checker.py
  src/pg4n/strange_having_checker.py
  src/pg4n/subquery_orderby_checker.py
  src/pg4n/subquery_select_checker.py
  src/pg4n/sum_distinct_checker.py
  src/pg4n/test/test_errfmt.py
Labels: refactor

#80 Fix/wrapper
  src/pg4n/psqlparser.py
  src/pg4n/psqlwrapper.py
  src/pg4n/test/test_psqlparser.py
  src/pg4n/test/test_psqlwrapper.py
Labels: enhancement, wrapper, refactor

#78 Feat/config
  src/pg4n/config_parser.py
  src/pg4n/config_reader.py
  src/pg4n/config_values.py
  src/pg4n/test/test_config_parser.py
Labels: enhancement

#83 Fixes outdated comment
  src/pg4n/config_reader.py
Labels: documentation

#84 Adds missing config values and a script generating those
  scripts/gen_config_values.bash
  src/pg4n/cmp_domain_checker.py
  src/pg4n/config_values.py
  src/pg4n/eq_wildcard_checker.py
  src/pg4n/implied_expression_checker.py
  src/pg4n/semanticrouter.py
  src/pg4n/strange_having_checker.py
  src/pg4n/subquery_order_by_checker.py
  src/pg4n/subquery_select_checker.py
  src/pg4n/sum_distinct_checker.py
  src/pg4n/test/test_config_parser.py
  src/pg4n/test/test_subquery_order_by_checker.py
Labels: bug
